config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :datasets do
    post :vote, on: :member
  end
  
  root to: 'datasets#index'
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
end

app/controllers/datasets_controller.rb
class DatasetsController < ActionController::Base
  def index
    @datasets = Dataset.all
  end
  
  def show
    @dataset = Dataset.find(params[:id])
  end
  
  def create
    @dataset = Dataset.create(params[:dataset].permit!)
    redirect_to datasets_path
  end
  
  def vote
    @dataset = Dataset.find(params[:id])
    current_user.likes @dataset
    redirect_to @dataset
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/datasets/index.html.slim
= form_for Dataset.new do |f|
  = f.label :title
  = f.text_field :title
  
  = f.label :content
  = f.text_area :content
  = f.submit

table
  tr
    td name
    td votes
  - @datasets.each do |dataset|
    tr
      td= link_to dataset.title, dataset
      td= dataset.votes_for.size

app/views/datasets/show.html.slim
h2= @dataset.title
p= simple_format @dataset.content
p
  b Votes: 
  = @dataset.votes_for.size
hr

= form_for @dataset, url: vote_dataset_path, method: :post do |f|
  = f.submit "Vote!"

app/views/layouts/application.html.slim
html lang="en"
  head
    meta charset="utf-8"
    title CFA Voting
    = javascript_include_tag 'https://cdn.shopify.com/s/assets/external/app.js'
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = yield
      hr
        footer
      span style="display:none"